version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - Kafka_Cluster
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - Kafka_Cluster
  kafka_manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000" # Kafka Manager web UI
    environment:
      - ZK_HOSTS=zookeeper:2181 # ZooKeeper host and port
      - APPLICATION_SECRET=secret # Change this to a secure value
    depends_on:
      - kafka
    networks:
      - Kafka_Cluster
networks:
  Kafka_Cluster:
    driver: bridge